name: Linter CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: validate Composer json
      run: make validate
    
    - name: Install dependency
      run: make install

    - name: Run linter
      run: make lint
